import type { LeaveType } from './types';

export const DEFAULT_LEAVE_TYPES: LeaveType[] = [
  {
    id: 'ferias',
    name: { pt: 'Férias', en: 'Vacation' },
    color: '#3B82F6',
    icon: '🏖️',
    annualAllowance: 22,
    deductsFrom: null,
    halfDayAllowed: true,
    isDefault: true,
    order: 1
  },
  {
    id: 'flex',
    name: { pt: 'Dias Flex', en: 'Flex Days' },
    color: '#8B5CF6',
    icon: '✨',
    annualAllowance: 0,
    deductsFrom: null,
    halfDayAllowed: false,
    isDefault: true,
    order: 2
  },
  {
    id: 'casamento',
    name: { pt: 'Casamento', en: 'Wedding' },
    color: '#EC4899',
    icon: '💒',
    annualAllowance: 15,
    deductsFrom: null,
    halfDayAllowed: false,
    isDefault: true,
    order: 3
  },
  {
    id: 'luto',
    name: { pt: 'Luto', en: 'Bereavement' },
    color: '#6B7280',
    icon: '🕯️',
    annualAllowance: 5,
    deductsFrom: null,
    halfDayAllowed: false,
    isDefault: true,
    order: 4
  },
  {
    id: 'baixa',
    name: { pt: 'Baixa Médica', en: 'Sick Leave' },
    color: '#EF4444',
    icon: '🏥',
    annualAllowance: null,
    deductsFrom: null,
    halfDayAllowed: false,
    isDefault: true,
    order: 5
  },
  {
    id: 'meio-dia',
    name: { pt: 'Meio Dia', en: 'Half Day' },
    color: '#F59E0B',
    icon: '⏰',
    annualAllowance: null,
    deductsFrom: 'ferias',
    halfDayAllowed: false,
    isDefault: true,
    order: 6
  },
  {
    id: 'parental',
    name: { pt: 'Licença Parental', en: 'Parental Leave' },
    color: '#14B8A6',
    icon: '👶',
    annualAllowance: null,
    deductsFrom: null,
    halfDayAllowed: false,
    isDefault: true,
    order: 7
  }
];

export const PORTUGAL_MUNICIPALITIES: string[] = [
  'Lisboa',
  'Porto',
  'Vila Nova de Gaia',
  'Aveiro',
  'Braga',
  'Coimbra',
  'Faro',
  'Leiria',
  'Viseu',
  'Setúbal',
  'Guimarães',
  'Viana do Castelo',
  'Barcelos',
  'Matosinhos',
  'Amadora',
  'Santana',
  'Almada',
  'Loures',
  'Oeiras',
  'Cascais',
  'Sintra',
  'Odivelas',
  'Seixal',
  'Maia',
  'Gondomar',
  'Valongo',
  'Santo Tirso',
  'Matosinhos',
  'Vila do Conde',
  'Póvoa de Varzim',
  'Trofa',
  'Fafe',
  'Vila Nova de Famalicão',
  'Ribeira Grande',
  'Ponta Delgada',
  'Angra do Heroísmo',
  'Horta',
  'Funchal',
  'Câmara de Lobos',
  'Funchal',
  'Porto Santo',
  'Alcobaça',
  'Nazaré',
  'Caldas da Rainha',
  'Obidos',
  'Peniche',
  'Torres Vedras',
  'Alenquer',
  'Lourinhã',
  'Cadaval',
  'Santarém',
  'Abrantes',
  'Torres Novas',
  'Entroncamento',
  'Mação',
  'Sardoal',
  'Ferreira do Zêzere',
  'Ourém',
  'Leiria',
  'Marinha Grande',
  'Pombal',
  'Figueira da Foz',
  'Montemor-o-Velho',
  'Cantanhede',
  'Mealhada',
  'Vagos',
  'Mira',
  'Coimbra',
  'Arganil',
  'Góis',
  'Lousã',
  'Miranda do Corvo',
  'Oliveira do Hospital',
  'Pampilhosa da Serra',
  'Tábua',
  'Vila Nova de Poiares',
  'Aveiro',
  'Águeda',
  'Albergaria-a-Velha',
  'Anadia',
  'Arouca',
  'Castelo de Paiva',
  'Espinho',
  'Estarreja',
  'Santa Maria da Feira',
  'Ílhavo',
  'Ovar',
  'São João da Madeira',
  'Sever do Vouga',
  'Vale de Cambra',
  'Vila Nova de Gaia',
  'Arouca',
  'Gondomar',
  'Maia',
  'Matosinhos',
  'Porto',
  'Póvoa de Varzim',
  'Trofa',
  'Valongo',
  'Vila do Conde',
  'Vila Nova de Gaia',
  'Braga',
  'Barcelos',
  'Esposende',
  'Fafe',
  'Guimarães',
  'Póvoa de Lanhoso',
  'Vieira do Minho',
  'Vila Nova de Famalicão',
  'Vila Verde',
  'Celorico de Basto',
  'Amares',
  'Caminha',
  'Melgaço',
  'Monção',
  'Paredes de Coura',
  'Ponte da Barca',
  'Valença',
  'Viana do Castelo',
  'Vila Nova de Cerveira',
  'Bragança',
  'Macedo de Cavaleiros',
  'Miranda do Douro',
  'Mirandela',
  'Vila Flor',
  'Vimioso',
  'Vinhais',
  'Alfândega da Fé',
  'Freixo de Espada à Cinta',
  'Torre de Moncorvo',
  'Vila Nova de Foz Côa',
  'Chaves',
  'Boticas',
  'Montalegre',
  'Ribeira de Pena',
  'Valpaços',
  'Vila Pouca de Aguiar',
  'Murça',
  'Alijó',
  'Armamar',
  'Lamego',
  'Mesão Frio',
  'Peso da Régua',
  'Santa Marta de Penaguião',
  'São João da Pesqueira',
  'Sátão',
  'Tarouca',
  'Trancoso',
  'Vila Nova de Paiva',
  'Aguiar da Beira',
  'Almeida',
  'Celorico da Beira',
  'Fornos de Algodres',
  'Gouveia',
  'Guarda',
  'Mêda',
  'Pinhel',
  'Sabugal',
  'Seia',
  'Trancoso',
  'Vila Nova de Foz Côa',
  'Castelo Branco',
  'Belmonte',
  'Covilhã',
  'Fundão',
  'Idanha-a-Nova',
  'Oleiros',
  'Penamacor',
  'Proença-a-Nova',
  'Sertã',
  'Vila de Rei',
  'Vila Velha de Ródão',
  'Portalegre',
  'Alter do Chão',
  'Arronches',
  'Avis',
  'Campo Maior',
  'Crato',
  'Elvas',
  'Fronteira',
  'Gavião',
  'Marvão',
  'Monforte',
  'Nisa',
  'Ponte de Sor',
  'Sardoal',
  'Ammaia',
  'Beja',
  'Aljustrel',
  'Alvito',
  'Barrancos',
  'Beja',
  'Castro Verde',
  'Cuba',
  'Ferreira do Alentejo',
  'Moura',
  'Odemira',
  'Ourique',
  'Serpa',
  'Vidigueira',
  'Évora',
  'Alandroal',
  'Arraiolos',
  'Borba',
  'Estremoz',
  'Évora',
  'Montemor-o-Novo',
  'Mora',
  'Mourão',
  'Portel',
  'Redondo',
  'Reguengos de Monsaraz',
  'Vila Viçosa',
  'Vendas Novas',
  'Açores',
  'Aveiro',
  'Braga',
  'Bragança',
  'Castelo Branco',
  'Faro',
  'Guarda',
  'Leiria',
  'Lisboa',
  'Portalegre',
  'Porto',
  'Santarém',
  'Setúbal',
  'Viana do Castelo',
  'Vila Real',
  'Viseu'
];
